site_name: AlchemyDocs
docs_dir: 'app/docs'
site_dir: '.tmp/documentation'
pages:
- [index.md, Home]
- [Contributing.md, Contributing]
- [Nodes.md, Nodes]
- [Examples.md, Examples]
# - [examples.md, Exampless]
# - [examples/example.md, Examples]
# - [examples/example2.md]
# - [examples/example3.md]
theme: readthedocs

# examples
